# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 01:45
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyftp', '0003_auto_20170903_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Download counter'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Upload date'),
        ),
    ]
