# Generated by Django 2.0.2 on 2018-03-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pyftp', '0004_auto_20170904_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Source'),
        ),
    ]
