# Generated by Django 2.0.2 on 2018-04-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20180308_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'ordering': ['upload_date', 'count']},
        ),
    ]
