# Generated by Django 2.0.2 on 2018-05-20 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('storage', '0008_auto_20180505_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'ordering': ['upload_date', 'count'], 'verbose_name': 'File'},
        ),
    ]
