# Generated by Django 2.0.2 on 2018-04-16 15:22

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Publication date')),
                ('description', models.TextField(max_length=100000, verbose_name='Description')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Publication date')),
                ('entry', ckeditor_uploader.fields.RichTextUploadingField(max_length=2000, verbose_name='Entry')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=100000, verbose_name='Content')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
