# Generated by Django 2.0.2 on 2018-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='blog.CategoryModel'),
        ),
    ]
