# Generated by Django 2.0.2 on 2018-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180417_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.CategoryModel'),
        ),
    ]
