# Generated by Django 2.0.2 on 2018-03-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_auto_20180308_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(verbose_name='Publication date'),
        ),
    ]
