# Generated by Django 2.0.2 on 2018-04-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180417_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.TagModel', verbose_name='Tags'),
        ),
    ]
