# Generated by Django 2.0.2 on 2018-03-08 19:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_auto_20180308_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Publication date'),
        ),
    ]
