# Generated by Django 2.0.2 on 2018-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180308_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='entry',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
