# Generated by Django 2.0.2 on 2018-05-20 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_auto_20180427_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-datetime'], 'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'ordering': ['title'], 'verbose_name': 'Tag'},
        ),
    ]
