# Generated by Django 2.0.3 on 2018-03-30 19:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180330_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='entry',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2000),
        ),
    ]
